// Льготники
export const BENEFICIARIES_UPLOAD = '@@Graalex/BENEFICIARIES_UPLOAD';
export const BENEFICIARIES_SUSSES = '@@Graalex/BENEFICIARIES_SUSSES';
export const BENEFICIARIES_FAILURE = '@@Graalex/BENEFICIARIES_FAILURE';
